version: 2.1

orbs:
  win: circleci/windows@5.0

jobs:
  build:
    executor:
      name: win/default
      size: medium
    steps:
      - checkout
      - run:
          name: Install Node.js
          command: choco install nodejs-lts -y
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build Windows exe
          command: npm run build
      - store_artifacts:
          path: dist
          destination: dist

workflows:
  build-and-package:
    jobs:
      - build
